name: pp test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: test pr
    runs-on: ubuntu-latest
    
    container: 
      image: jetscape/base:v1.3
      options: --user root
      
    steps:
      
    - name: Checkout JETSCAPE-analysis
      uses: actions/checkout@v2

    - name: Checkout JETSCAPE
      uses: actions/checkout@v2
      with:
        repository: JETSCAPE/JETSCAPE
        path: JETSCAPE
        
    - name: Build JETSCAPE
      run: |
        cd $GITHUB_WORKSPACE/JETSCAPE
        mkdir build
        cd build
        cmake ..
        make
      
